// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TpFinal.Models;

namespace TpFinal.Migrations
{
    [DbContext(typeof(ContextBD))]
    partial class ContextBDModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TpFinal.Models.Article", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateSoumission");

                    b.Property<int>("ParticipantId");

                    b.Property<string>("Titre");

                    b.HasKey("ID");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("TpFinal.Models.Membre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ParticipantId");

                    b.HasKey("ID");

                    b.ToTable("Membres");
                });

            modelBuilder.Entity("TpFinal.Models.MembreArticle", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MembreId");

                    b.Property<int>("Note");

                    b.HasKey("ArticleId");

                    b.ToTable("MembreArticles");
                });

            modelBuilder.Entity("TpFinal.Models.Organisateur", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeUtilisateur")
                        .IsRequired();

                    b.Property<int>("ParticipantId");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Role")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Organisateurs");
                });

            modelBuilder.Entity("TpFinal.Models.Paiement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatePaiement");

                    b.Property<decimal>("Montant");

                    b.Property<int>("ParticipantId");

                    b.HasKey("ID");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("TpFinal.Models.Participant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Affiliation")
                        .IsRequired();

                    b.Property<DateTime>("DateInscription");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<decimal>("Montant");

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.Property<string>("Prenom")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("TpFinal.Models.Session", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateSoumission");

                    b.Property<int>("MembreId");

                    b.Property<string>("Titre");

                    b.HasKey("ArticleId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TpFinal.Models.Spécialité", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("MembreId");

                    b.HasKey("ID");

                    b.ToTable("Spécialités");
                });

            modelBuilder.Entity("TpFinal.Models.VersionArticle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleId");

                    b.Property<int>("Version");

                    b.HasKey("ID");

                    b.ToTable("VersionArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
